#!/usr/bin/env bash

# Temporary, hardcoded.  TODO: make programatic
export REGION=us-west-2
export AMI_ID=ami-2a38b14a
export SUBNET_ID_1=subnet-2b9c2f62
export SUBNET_ID_2=subnet-5ea93039
export SUBNET_ID_3=subnet-37d9cd6f
export RTB_ID=rtb-08cf236e
export SG_ID=sg-50cddb28
export HOSTED_ZONE_NAME=illumin8.us
export HOSTED_ZONE_ID=Z2WYTNUPD8MNNW
export VOL_ID=vol-0c4e135dfc61d3656
export VPC_ID=vpc-567e3831
export ALLOCATION_ID=eipalloc-b68871d0
export PUBLIC_IP_ADDRESS=54.70.212.114

# Rancher
export RANCHER_ENV=default
export COMPOSE_PROJECT_NAME=example-stack # Stack Name
export RANCHER_LB_NAME=example-load-balancer
export RANCHER_URL=http://rancher.illumin8.us:8080
export COMPOSE_FILE=rancher/$RANCHER_ENV/$COMPOSE_PROJECT_NAME/docker-compose.yml
