version: '2'
services:
  example-webserver:
    image: thewoolleyman/docker-webserver-example:20170323T035310-4d57408
    stdin_open: true
    tty: true
    ports:
    - 63199:80/tcp
    labels:
      io.rancher.container.pull_image: always
  example-load-balancer:
    image: rancher/lb-service-haproxy:v0.6.2
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
